definitions:
  env_versions: &env_versions
    flutter: 3.13.9
    xcode: latest
    cocoapods: 1.14.2
  scripts:
    - &setup_local_props
      name: Set up local.properties
      script: |
        echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
    - &install_dependencies
      name: Installing Dependencies
      script: |
        flutter packages pub get
    - &check_format
      name: Checking Format
      script: |
        dart format --output=none --set-exit-if-changed .
    - &exec_flutter_analyze
      name: Analyzing Code (flutter analyze)
      script: |
        flutter analyze
    - &ios_auto_signing
      name: Set up code signing settings on Xcode project
      script: |
        xcode-project use-profiles

workflows:
  flutter-analyze-test-workflow:
    name: Flutter Analyze & Test
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      <<: *env_versions
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - ~/.gradle/caches
        - ~/Library/Caches/CocoaPods
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: "*"
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      - *install_dependencies
      - *check_format
      - *exec_flutter_analyze

    artifacts:
      - build/**/outputs/apk/**/*.apk
      - build/**/outputs/bundle/**/*.aab
      - build/**/outputs/**/mapping.txt
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - build/windows/**/*.msix
      - flutter_drive.log

  android-staging-playstore-workflow:
    name: Android Staging PlayStore Publishing
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      <<: *env_versions
      groups:
        - brooklyn-app-stg
      android_signing:
        - keystore_reference_stg
      vars:
        APP_FLAVOR: stg
        GOOGLE_PLAY_TRACK: alpha
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true
      cancel_previous_builds: true
    scripts:
      - *setup_local_props
      - *install_dependencies
      - *check_format
      - *exec_flutter_analyze
      - name: Building Android
        script: |
          flutter build appbundle --release --flavor stg --dart-define=FLAVOR=stg \
            --build-number=$PROJECT_BUILD_NUMBER
    artifacts:
      - build/**/outputs/bundle/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: $GOOGLE_PLAY_TRACK
        submit_as_draft: true
