name: PR Auto label and assign

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  contents: read
  pull-requests: write

jobs:
  pr_auto_label_and_assign:
    runs-on: ubuntu-latest
    steps:
      - name: Add Label
        uses: actions/labeler@v5

      - name: Auto Assign
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: ".github/auto_assignment.yml"
