name: PR Auto label and assign

on:
  push:
    branches:
      - main
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  contents: read

jobs:
  pr_auto_label_and_assign:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Add Label
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/labeler.yml

      - name: Check if PR is ready for review
        id: check_ready_for_review
        run: echo "::set-output name=is_ready::$(if [ ${{ github.event_name }} == 'pull_request' ] && [ ${{ github.event.action }} == 'opened' ] || [ ${{ github.event.action }} == 'reopened' ] || [ ${{ github.event.action }} == 'ready_for_review' ]; then echo true; else echo false; fi)"

      - name: Auto Assign
        uses: kentaro-m/auto-assign-action@v1.1.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: ".github/auto_assignment.yml"
